default_language_version:
  python: python3.12

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.5
  hooks:
    # Run the formatter.
    - id: ruff-format
    # Run the linter.
    - id: ruff
      args: [ --fix ]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-merge-conflict
    - id: check-yaml
    - id: debug-statements
    - id: detect-private-key
